import React from "react"
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app & notificayions by courier',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
